# Generated by Django 3.2.16 on 2023-02-25 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_follow_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='follow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.follow'),
        ),
    ]
